#include "viz_csv.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

mv_status_t csv_export_fn(const char* filepath, scalar_field_fn f, void* ud, double xmin, double xmax, int steps)
{
    if (!filepath || !f || steps < 2) return MV_ERR_NULL_PTR;
    FILE*fp = fopen(filepath, "w");
    if (!fp) return MV_ERR_ALLOC;
    MVec xv;
    mv_status_t st = mvec_create(&xv, 1);
    if (st != MV_OK)
    {
        fclose(fp);
        return st;
    }
    fprintf(fp, "x,y\n");
    double dx = (xmax - xmin) / (steps - 1);
    for (int i = 0; i < steps; ++i)
    {
        double x = xmin + i * dx;
        xv.data[0] = x;
        double y = f(&xv, ud);
        fprintf(fp, "%.8g,%.8g\n", x, y);
    }
    mvec_destroy(&xv);
    fclose(fp);
    return MV_OK;
}
mv_status_t csv_export_fn2d(const char* filepath, scalar_field_fn f, void* ud, double x0, double x1, int nx, double y0, double y1, int ny)
{
    if (!filepath || !f || nx < 2 || ny < 2) return MV_ERR_NULL_PTR;
    FILE*fp = fopen(filepath, "w");
    if (!fp) return MV_ERR_ALLOC;
    MVec xv;
    mv_status_t st = mvec_create(&xv, 2);
    if (st != MV_OK)
    {
        fclose(fp);
        return st;
    }
    fprintf(fp, "x,y,z\n");
    double dx = (x1 - x0) / (nx - 1);
    double dy = (y1 - y0) / (ny - 1);
    for (int i = 0; i < nx; ++i)
    {
        xv.data[0] = x0 + i * dx;
        for (int j = 0; j < ny; ++j)
        {
            xv.data[1] = y0 + j * dy;
            double z = f(&xv, ud);
            fprintf(fp, "%.8g,%.8g,%.8g\n", xv.data[0], xv.data[1], z);
        }
        fprintf(fp, "\n");
    }
    mvec_destroy(&xv);
    fclose(fp);
    return MV_OK;
}
mv_status_t csv_export_mat(const char* filepath, const MMat* m)
{
    if (!filepath || !m) return MV_ERR_NULL_PTR;
    FILE *fp = fopen(filepath, "w");
    if (!fp) return MV_ERR_ALLOC;
    for (size_t j = 0; j < m->cols; ++j)
        fprintf(fp, "col_%zu%s", j, j + 1 < m->cols ? "," : "\n");
    for (size_t i = 0; i < m->rows; ++i)
    {
        for (size_t j = 0; j < m->cols; ++j)
            fprintf(fp, "%.8g%s", MMAT_AT(m, i, j), j + 1 < m->cols ? "," : "\n");
    }
    fclose(fp);
    return MV_OK;
}
mv_status_t csv_export_vec(const char* filepath, const MVec* v)
{
    if (!filepath || !v) return MV_ERR_NULL_PTR;
    FILE*fp = fopen(filepath, "w");
    if (!fp) return MV_ERR_ALLOC;
    fprintf(fp, "index,value\n");
    for (size_t i = 0; i < v->dim; ++i)
        fprintf(fp, "%zu,%.8g\n", i, v->data[i]);
    fclose(fp);
    return MV_OK;
}
mv_status_t gnuplot_write_1d(const char* script_path, const char* csv_path, const char* png_path, const char* title)
{
    if (!script_path || !csv_path || !png_path) return MV_ERR_NULL_PTR;
    FILE *fp = fopen(script_path, "w");
    if (!fp) return MV_ERR_ALLOC;
    fprintf(fp, "# Auto-generated by MathVista-C  (gnuplot 5+)\n");
    fprintf(fp, "set terminal pngcairo size 900,600 enhanced font 'Menlo,11'\n");
    fprintf(fp, "set output '%s'\n", png_path);
    fprintf(fp, "set title  '%s'\n", title ? title : "Function Plot");
    fprintf(fp, "set xlabel 'x'\n");
    fprintf(fp, "set ylabel 'f(x)'\n");
    fprintf(fp, "set grid\n");
    fprintf(fp, "set datafile separator ','\n");
    fprintf(fp, "set key top right\n");
    fprintf(fp, "# Skip CSV header row\n");
    fprintf(fp, "plot '%s' every ::1 using 1:2 with lines lw 2 title 'f(x)'\n", csv_path);
    fclose(fp);
    return MV_OK;
}
mv_status_t gnuplot_write_2d(const char* script_path, const char* csv_path, const char* png_path, const char* title, int nx, int ny)
{
    if (!script_path || !csv_path || !png_path) return MV_ERR_NULL_PTR;
    (void)nx; (void)ny;
    FILE*fp = fopen(script_path, "w");
    if (!fp) return MV_ERR_ALLOC;
    fprintf(fp, "# Auto-generated by MathVista-C  (gnuplot 5+)\n");
    fprintf(fp, "set terminal pngcairo size 900,700 enhanced font 'Menlo,10'\n");
    fprintf(fp, "set output '%s'\n", png_path);
    fprintf(fp, "set title '%s'\n", title ? title : "Surface Plot");
    fprintf(fp, "set xlabel 'x'\n");
    fprintf(fp, "set ylabel 'y'\n");
    fprintf(fp, "set zlabel 'f(x,y)'\n");
    fprintf(fp, "set hidden3d\n");
    fprintf(fp, "set pm3d depthorder\n");
    fprintf(fp, "set palette rgbformulae 33,13,10\n");
    fprintf(fp, "set datafile separator ','\n");
    fprintf(fp, "splot '%s' every ::1 using 1:2:3 with pm3d title ''\n", csv_path);
    fclose(fp);
    return MV_OK;
}