# Auto-generated by MathVista-C  (gnuplot 5+)
set terminal pngcairo size 900,700 enhanced font 'Menlo,10'
set output 'output/gauss2d.png'
set title 'Gaussian  e^{-(x²+y²)/2}'
set xlabel 'x'
set ylabel 'y'
set zlabel 'f(x,y)'
set hidden3d
set pm3d depthorder
set palette rgbformulae 33,13,10
set datafile separator ','
splot 'output/gauss2d.csv' every ::1 using 1:2:3 with pm3d title ''
