# Auto-generated by MathVista-C  (gnuplot 5+)
set terminal pngcairo size 900,600 enhanced font 'Menlo,11'
set output 'output/sinc.png'
set title  'sinc(x) = sin(x)/x'
set xlabel 'x'
set ylabel 'f(x)'
set grid
set datafile separator ','
set key top right
# Skip CSV header row
plot 'output/sinc.csv' every ::1 using 1:2 with lines lw 2 title 'f(x)'
